### ISSUE TITLE
[BUG]No config.json generate

### ISSUE THREAD

**Issue by nobleman80** [hyecheol123/Cloudflare-Public-Dynamic-IP-Update#13]
Hi there is no config.json generate after successful running configure.bash.

**Comment by nobleman80** [comment]
Hi, I can't run the script as it's said json file does not exist. Therefore no record has been update.

Yes git bash is able to install jq. Same as synology. Both ask if want to add the domains Y/N. And success msg appeared , it say will save to config.json but the file does not generated.

Or should I create the config.json file myself?

**Comment by hyecheol123** [comment]
I run the code on git bash, it works without error (`config.json` created); however, you need to modify code (add two lines of code) to make it work there.
It is because I "installed" jq by creating an alias of the path pointing to where my `jq` binaries for Windows located. To use the alias on the bash shell, you need to add the alias on your `~/.bashrc`, then load the file once the shell script starts.

To load the file once the shell script starts, you need to add 
```
shopt -s expand_aliases
source ~/.bashrc
```
before the code starts.

For other systems, Mac and Synology, I have no way to test on those, as I do not have access to the systems. Hope this comments on the Git Bash for Windows guide you find the answers on other systems, too. I will modify codes and upload those on the separated branch; so that you can test it.

**Comment by hyecheol123** [comment]
Check Branch: git_bash_alias_issue_#13

**Comment by nobleman80** [comment]
Thanks for your reply. unfortunately i m unable to make it work. are you able to send me a sample of config.json? i will manually update the domains and A records.

**Comment by hyecheol123** [comment]
Did you get an error like this?
```
./configure.bash: line 45: [: 0: unary operator expected
```

I am trying to debug my code while I recap myself what information is stored in `config.json`, and I found out that those errors sometimes occur, which makes configuration file not properly generated.

**Comment by hyecheol123** [comment]
BTW, the template for `config.json` will be provided to you within 24 hours. I am almost finish recap which information is used. All I need to do is write some description how to find those information.

**Comment by hyecheol123** [comment]
The command uses DNS record update API of Cloudflare. (https://api.cloudflare.com/#dns-records-for-a-zone-update-dns-record)

The `config.json` need to contain API key with `Zone:Read` and `DNS:Edit` permissions and a list, update-target, containing information of record name, record identifier, and zone identifier.

The example of `config.bash` is attached below.

``` config.json
{
  api: <YOUR-API-KEY>
  update-target: [
    {
      name: <NAME-OF-DNS-RECORD/URL-TYPE>
      id: <RECORD-IDENTIFIER>
      zone_id: <ZONE-IDENTIFIER>
    }
  ]
}
```

Hope this helps

**Comment by hyecheol123** [comment]
Due to inactivity, this issue is closed

If @nobleman80 you want to reopen it, please feel free to do so.
