### ISSUE TITLE
[FEATURE] JSON format config file, Configurate Script, Cloudflare Multi-user case?

### ISSUE THREAD

**Issue by hyecheol123** [hyecheol123/Cloudflare-Public-Dynamic-IP-Update#7]
Modifying configuration file might be bothersome.
Add interactive configuration scripts to generate configuration file.

The new configuration file will be written as json file.
Support both appending mode and overwrite mode.

**Comment by hyecheol123** [comment]
- Change config file to JSON format
- Use Python for script
  - Python is more convenient in dealing with JSON format.

**Comment by hyecheol123** [comment]
TODOs

- JSON Type config file
- config file auto generator
- Error codes and messages
- Write script in Python as it is better on handling JSON formats (than shell scripts)

**Comment by Rp70** [comment]
I have some feedback:
- Config file with INI format is suitable to this project rather than JSON or YAML. You can parse INI format with Bash, just google it. If you go with INI, I think you can have a sample config file like this
```ini
; Main section with options for the script.
[main]
; Email system admin if something goes wrong.
admin_email=me@domain.com

; Global section: global scope options for other sections
[global]
Auth-Key=[Your_CloudFlare_API_Auth_Key]
Auth-Email=[Your_CloudFlare_Account_Email]

; Custom section for domain.net
[domain.net]
Update-Target="domain.net sub.domain.net"

; Custom section for example.net
[example.net]
Update-Target="example.net sub.example.net"

```
The above sample config talks about multiple domains support but I think it's not neccessary because we can setup CNAME for additional domains. That's just an idea while wring this comment. I also think that Record-Type isn't neccessary too. Because there are only A & AAAA that needs IPv4 or IPv6. TXT may content IP but usually for setting up [SPF](https://en.wikipedia.org/wiki/Sender_Policy_Framework#Implementation) which isn't advised to use dynamic IPs for sending emails.
- Config file auto generator is good feature to have but it should be a low priority.
- Error codes & messages: Yes! It helps with error & helpful messages to advise users what to do to run the script.
- Switch to Python: No! I think it's better to have it in Bash and make it more portable on other shells.  This script https://github.com/acmesh-official/acme.sh is an example of shell script actually works on shell environments.

FYI, before working with your script, I used https://github.com/ddclient/ddclient for a very long time. It's very stable. I never have any troubles with it but it's something overkill. However, I need something light weight and just do what it should do in oneshot. It should run even with normal user cron setup. I evenly will write a wrapper script to setup High Availability with Cloudflare for distant servers at work and at home for 2 projects. That sounds weird to setup High Availability with this script but my projects are a bit different. So I finally decided to use your script.

My background is PHP so I understand why you want to Python. In the past, I don't like shell scripts but the more you work with servers and shell scripts, you will like them.

Hope this helps.

**Comment by hyecheol123** [comment]
Thanks for the comments.
The primary reason I choose JSON was simple: it is more structured than simple text file. So, I am open with using **INI** format!! I really appreciate with your suggestion!!

I am also hesitate to use python, as this may not installed default, the initial reason why I decide to change my script to python is it will be more easy to deal with the JSON types. But as I found alternative container for configuration file, I will stick on bash. I understand Bash still have its own strengths.

For the domain record type, yeap, I found out that it is unrealistic to support more than one record type. Only A record and AAAA record supports IP address, and, as you know, IPv6 is not yet popular, so I believe it will be okay only to support A record. Once I have opportunity to work with IPv6-only server, I will add the support for AAAA record, but right now, I will stick with A record.

As this code was initially for my personal projects, I only decide to support Cloudflare (as I only using its service, not others), and thanks for using my code.

**Comment by hyecheol123** [comment]
#6 
- [ ] Enable feature to choose the record from the list of entries associated with the account
- [ ] Multi-user cases

**Comment by Rp70** [comment]
> #6

This fork uses env variables: https://github.com/cccrc/Cloudflare-Public-Dynamic-IP-Update which I think it's more flexible for calling by a wrapper. But the author hard coded it. But I have finally chosen your repo because I wanted to always up to date with your script and can contribute back.

**Comment by hyecheol123** [comment]
@Rp70 I checked about INI File, and it looks like there is no such "standardized" way to use INI files.
